version: "3"
services:
  my_app:
    build:
      context: ./
      dockerfile: back/Dockerfile
    container_name: back
    ports:
      - "5000:5000"
    volumes:
      - downloads_volume:/back/downloads

# environment:
#   # для отладки (при запуске в релиз убрать!)
#   - FLASK_ENV=development
#   ## Позволяет отслеживать процесс работы приложения в командной строке
#   - PYTHONUNBUFFERED=True   

volumes:
  downloads_volume: